{% set name = "wisper" %}
{% set version = "2.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: ce17bc5c3a166f241a2e6613848b025c8146fce2defba505920c1d1f3f88fae6

build:
  noarch: generic
  number: 2
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A micro library providing objects with Publish-Subscribe capabilities. Both synchronous (in-process) and asynchronous (out-of-process) subscriptions are supported.'
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/krisleech/wisper/

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
