travis:
  secure:
    BINSTAR_TOKEN: JFRRklLlM4CmLAPZP3o1XorMdRkOH8XAd+A7gz5PTb/P2mkl83xaLCcFvhh60iGZEFlnX92pBAwvPyi5YAUxHbpRJ229oeq2UqFA30snd7k6TNFNuokNzw1k9f9NK9Z1FUFZxjMJMSXZBM/HV1NR22N1S4JeHfpQ5BtcCkeqYCUZChmS1UzDCCBJYrIznLnxZA/4PMdYr7HuB3W1bpS+p1W8rfvti6RD87Z/lQ9gCtFsEi+czYfBJCND5qlPwnvHri03ulL8Xgskm20j/Bl3h4KhrJ4O7nLc8tTuNQh9UC1KRI0QFKjLrBeUyyxgCxnQ2fTNiEv7ayYFf4LgYl8UpJkXXsIgzfE2v+JmJjE52o+L45CfnNY5LQnT4iXHhhk4Hc6VmwviJLuNorfaY4q/C32j3be+MMlhU3ecCS/+t9IvKCDewrLKu3k0tffWHEF/LcsC9kOWWWIykk71vkBO7LwuAd8QZsZSrXQ5iK00auYHbz3GZXBFddTZmX7Q0SwaLS/hPBKyWIL4+Yd8vmmpnFUDfdzRcYT6zfmqCPDSCONFaJqCFbU2OKZiwsVK93BRtA9nbbyXmEv50HQI4Chp9U/Tn0N+MX9amXNuru9Mn+NMjpeMB6PEzggpsCFsDDJbgopMKRZbDgcImGiVYIULCRhkAq4Szq6NMI365cC7np0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
