travis:
  secure:
    BINSTAR_TOKEN: hCNuFeSYwS+DB5mlbNDL8fd0Fc8rjDitqWubkEgx+IKwR9FAPFSoinBJUxl+WvWLaFfnBQdUKeowrZzGg9YfjM9ecNIWNRxJiGyyymKrAFGgESrv5Yslm2tEE2t3icfP+Nb7w/JYQSt++Y1/R7uaGNh1AtiUi+e/GW0MjWDKpNpXARabk1BVKMGKaDvRq5yxkmXST1pwPZ+9atp3VYZh0lvktKRrWTg72CbIgYCe78Q06KmHKK/qyeleqjcuRE2eXf0209k0UyZroM16S7UWTyl63YyjMY25PSb89nALSb+FDo90xDYQ7/GtqfZ9YUEp65/h3OUgRDLu3oSlw3nlLwpB7QcZzw60rYPgrHOIrzHazlg+CEtfOfiarm1fI1LBcWKA20VeDk6acDJncMPovA7fwYoe0vxKS/nbd1ZF3ote7VQMm4hFyN0GjBP4lFoX84M1uMGmJp0+F+7lBx7CUdEJTh2TjssLJEur2iVJ/7AkX7LEY42E1CKquGkddUmyxa6E0XpShmtF69gF9mgxFuvyUS+K3erzGmvWcsnrweKRHUSJbnanUlnmrctFr8S9v458E2YXe7A9Xo7mNE0FeGDPw4/ACBnb7nfQPEYje4y7vGtHA9Xq0Z3ZeWNvEokpwGVWXjzJCHKWbg8W3a6ERtMMIhYB216qdtGtpAiLvZc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
